apiVersion : apps/v1
kind: Deployment
metadata:
  name: "trips"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "trips"
  template:
    metadata:
      labels:
        app: "trips"
    spec:
      containers:
        - name: "trips"
          image: "aqaksacr.azurecr.io/trips"
          ports:
          - containerPort: 81