apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aqakscluster-84bd"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aqakscluster-84bd"
  template:
    metadata:
      labels:
        app: "aqakscluster-84bd"
    spec:
      containers:
        - name: "aqakscluster-84bd"
          image: "aqaksacr.azurecr.io/trips"
          ports:
          - containerPort: 80