apiVersion: v1
kind: Service
metadata:
    name: "user-profile"
    labels:
        app: "user-profile"
spec:
    type: ClusterIP
    ports:
    - port: 82
      targetPort: 82
      protocol: TCP
      name: http
    selector:
        app: "user-profile"