apiVersion: v1
kind: Service
metadata:
    name: "aqakscluster-7bc6"
    labels:
        app: "aqakscluster-7bc6"
spec:
    type: ClusterIP
    ports:
    - port: 88
      targetPort: 88
      protocol: TCP
      name: http
    selector:
        app: "aqakscluster-7bc6"