apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: tripviewer-ingress
  namespace: web
spec:
  rules:
  - host: aksaqaksla-aks-rg-aqakslab-c11348-d8ccbbbf.hcp.canadacentral.azmk8s.io
    http:
      paths:
      - backend:
          serviceName: tripviewer
          servicePort: 80
        path: /
      - backend:
          serviceName: tripviewer
          servicePort: 80
        path: /UserProfile
      - backend:
          serviceName: tripviewer
          servicePort: 80
        path: /Trips