apiVersion: 2018-10-01
location: eastus
name: simulator-app-registrycwy3531
properties:
  containers:
  - name: simulator
    properties:
      image: registrycwy3531.azurecr.io/simulator:1.0
      resources:
        requests:
          cpu: 2
          memoryInGb: 1.5
      ports:
      - port: 80
  - name: prometheus
    properties:
      image: registrycwy3531.azurecr.io/prometheus-sim:1.0
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 9090
  - name: grafana
    properties:
      image: registrycwy3531.azurecr.io/grafana-sim:1.0
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 3000
  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: '80'
    - protocol: tcp
      port: '9090'
    - protocol: tcp
      port: '3000'
    dnsNameLabel: simulatorregistrycwy3531
  imageRegistryCredentials:
  - server: registrycwy3531.azurecr.io
    username: registrycwy3531
    password: b6mUdW2fM1SXuZF0yQJ8VOZViyZ/4aTs
tags: null
type: Microsoft.ContainerInstance/containerGroups