on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrhackfestaqakslab.azurecr.io
        username: ${{ secrets.acr_acrhackfestaqakslab_username }}
        password: ${{ secrets.acr_acrhackfestaqakslab_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/src/poi" -f  "src/poi/Dockerfile" -t acrhackfestaqakslab.azurecr.io/aksaqakslab:${{ github.sha }} --label dockerfile-path=src/poi/Dockerfile
        docker push acrhackfestaqakslab.azurecr.io/aksaqakslab:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksaqakslab_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep api | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace api`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: api
        container-registry-url: acrhackfestaqakslab.azurecr.io
        container-registry-username: ${{ secrets.acr_acrhackfestaqakslab_username }}
        container-registry-password: ${{ secrets.acr_acrhackfestaqakslab_password }}
        secret-name: aksaqakslabdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: api
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acrhackfestaqakslab.azurecr.io/aksaqakslab:${{ github.sha }}
        imagepullsecrets: |
          aksaqakslabdockerauth
