on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aqaksacr.azurecr.io
        username: ${{ secrets.acr_aqaksacr_username }}
        password: ${{ secrets.acr_aqaksacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/charts/tripviewer" -f  "charts/tripviewer/Dockerfile" -t aqaksacr.azurecr.io/tripviewer:${{ github.sha }} --label dockerfile-path=charts/tripviewer/Dockerfile
        docker push aqaksacr.azurecr.io/tripviewer:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aqakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep hack-web | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace hack-web`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: hack-web
        container-registry-url: aqaksacr.azurecr.io
        container-registry-username: ${{ secrets.acr_aqaksacr_username }}
        container-registry-password: ${{ secrets.acr_aqaksacr_password }}
        secret-name: aqaksclusterdockerauth
       
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: charts/tripviewer/helm
        releaseName: 'aks-helm-release'
        helm-version: 'latest' 
        silent: 'false'
        overrideFiles: |
          
        overrides: |
          replicas:2
          image.repository:aqaksacr.azurecr.io/tripviewer
          image.tag:${{ github.sha }}
          imagePullSecrets:
            -name:aqaksclusterdockerauth
      id: bake

    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: hack-web
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          aqaksacr.azurecr.io/tripviewer:${{ github.sha }}
        imagepullsecrets: |
          aqaksclusterdockerauth
